### ISSUE TITLE
[Plank Sack] Counter desyncs when repairing bridges in the Hallowed Sepulchre

### ISSUE THREAD

**Issue by fuzxi** [Enriath/external-plugins#52]
This issue is for the external plugin: {Plank Sack}

When repairing bridges in the Hallowed Sepulchre to reach coffins, the plank sack counter does not change until manually checking the sack. Repairing bridges consumes two of any plank type.

**Comment by Hydrox6** [comment]
Ah that would make sense, I didn't remember that there was something like that in the Sepulchre. I'll have to go look at that, might not be too hard.

**Comment by philzin** [comment]
It's been a while, but have you looked into this at all? Would be a really nice update.

**Comment by andmcadams** [comment]
I built my own local version a while back to fix this. The code I added is just copying the format of the MH handling, I avoided condensing the code for clarity. I'm pretty sure this code would fail if you are building a bridge and run out of nails without succeeding, but I haven't tested it since it doesn't apply to me. Might be a useful starting point
Diff: https://github.com/andmcadams/external-plugins/compare/plank-sack..plank_sack_sepulchre_patch

**Comment by Enriath** [comment]
> I built my own local version a while back to fix this. The code I added is just copying the format of the MH handling, I avoided condensing the code for clarity. I'm pretty sure this code would fail if you are building a bridge and run out of nails without succeeding, but I haven't tested it since it doesn't apply to me. Might be a useful starting point Diff: [andmcadams/external-plugins@`plank-sack..plank_sack_sepulchre_patch` (compare)](https://github.com/andmcadams/external-plugins/compare/plank-sack..plank_sack_sepulchre_patch)

That does look like it would cover most of it, though the animations being limited looks odd. You're also probably right that it would break if you ran out of nails, but you could probably check if the delta'd item was a plank (probably).

**Comment by SaffiCauthon** [comment]
I've noticed the same issue and would love to see this updated.
Has there been any progress on this since [andmcadams](https://github.com/andmcadams) commented earlier this year?
This would be a very nice (and greatly appreciated) QoL! 😄

**Comment by Enriath** [comment]
This will be fixed in v1.3.0, which is awaiting review. I'll close this issue when it's merged and available.

**Comment by SaffiCauthon** [comment]
Should now be live (https://github.com/runelite/plugin-hub/commit/89044db72b04e82eae52beb1a522af965be386ef), thank you once again.

![Today's the day](https://i.imgur.com/STUzsg5.gif)
